### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by szerzs-collab** [TheMadrasTechie/News-API-video-generator#1]
Hello dear friend!
Please help me).
Wanted to run your script. I replaced the API with my own. Run demo.py.
Nothing has been created except mp3 files :(
Screenshot: https://prnt.sc/vuPIXOj7fMQq

There is also a problem with the requirements.txt file.
I had to install everything manually:

newsapi-python:pip install newsapi-python
opencv-python:pip install opencv-python
urllib:pip install urllib3
numpy:pip install numpy
moviepy:pip install moviepy
mutagen:pip install mutagen
pillow:pip install Pillow
gtts:pip install gTTS

Installed correctly?

When executing the demo.py file, the following lines are obtained:

0
Cyber Monday graphics card deals live: all the best discounts going right now - Gamesradar
All the latest Cyber Monday graphics card deals as they come and as we find them - delivered straight to your peepers
https://cdn.mos.cms.futurecdn.net/rQWBWdQVCd8xwf3tXYPX4A-1200-80.jpg
Moviepy - Building video videos/video0.mp4.
MoviePy - Writing audio in video0TEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video videos/video0.mp4

t:   0%|▏                                                                    | 2/960 [00:00<01:12, 13.17it/s, now=None]issue
1
44 Best Apple Cyber Monday Deals (2022): Apple Watch, iPads, AirPods - WIRED
Need a new Apple Watch or iPhone case? Now's the time to snag one with Apple's Black Friday and Cyber Monday Deals.
https://media.wired.com/photos/637d41a7cfe6da8f54b1e5b1/191:100/w_1280,c_limit/19%20-%20Best%20Absolute%20Best%20Cyber%20Monday%20Deals%203.jpg
Moviepy - Building video videos/video1.mp4.
MoviePy - Writing audio in video1TEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video videos/video1.mp4

t:   0%|                                                                    | 2/1200 [00:00<01:06, 18.03it/s, now=None]issue
2
WTF?!?! Buy an iPhone 14 Pro, get a FREE iPad, Apple Watch & Beats headphones! - Digital Camera World
This. Is. UNBELIEVABLE. Get an iPhone 14 Pro and you can get a FREE iPad, Apple Watch and Beats Fit Pro Headphones FREE!!!
https://cdn.mos.cms.futurecdn.net/RxDb64wNrg7RS2K92PxK9V-1200-80.jpg
Moviepy - Building video videos/video2.mp4.
MoviePy - Writing audio in video2TEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video videos/video2.mp4

t:   0%|                                                                    | 2/1380 [00:00<01:09, 19.81it/s, now=None]issue
3
Best Cyber Monday smartwatch and fitness tracker deals - The Verge
If you’re overwhelmed by all the Black Friday and Cyber Monday smartwatch and fitness tracker deals, then look no further. We’ve rounded up the best of the best so you can buy with confidence this holiday season.
https://cdn.vox-cdn.com/thumbor/gtIBOe-4MbrR5YL4-Ykiy_TXsrY=/0x0:2040x1360/1200x628/filters:focal(883x579:884x580)/cdn.vox-cdn.com/uploads/chorus_asset/file/23952683/akrales_220811_226124_0146.jpg
Moviepy - Building video videos/video3.mp4.
MoviePy - Writing audio in video3TEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video videos/video3.mp4

t:   0%|                                                                    | 2/1260 [00:00<01:27, 14.40it/s, now=None]issue
4
This is Ferrari's Vision GT Car for Gran Turismo 7 - GTPlanet
Ferrari has finally unveiled its highly anticipated Vision GT project car during the Gran Turismo World Finals here in Monaco. As you might expect from the famous Italian company, it’s quite a looker! Flavio Manzoni, Senior Vice President of Design at Ferrari…
https://www.gtplanet.net/wp-content/uploads/2022/11/Ferrari_Vision_GT_03.jpg
issue
5
The best early Cyber Monday deals you can get on 4K TVs - The Verge
Getting a new TV is a big deal, we know. Let our pick of the best Cyber Monday deals on TVs help you find the best fit for your needs.
https://cdn.vox-cdn.com/thumbor/Bta02JlRBwQ10iO36mxhoCxknVI=/0x0:2040x1360/1200x628/filters:focal(1020x680:1021x681)/cdn.vox-cdn.com/uploads/chorus_asset/file/23215200/cwelch_220119_4998_0001.jpg
Moviepy - Building video videos/video5.mp4.
MoviePy - Writing audio in video5TEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video videos/video5.mp4

t:   0%|                                                                            | 0/1020 [00:00<?, ?it/s, now=None]issue
6
With Black Friday in the Rearview, Various Beats Headphones Remain at All-time Lows - CNET
Just because Black Friday is over, that doesn't mean the deals are. Some great deals remain for Cyber Monday.
https://www.cnet.com/a/img/resize/14874779c26f86ef024a9a324791cead41312f5c/hub/2022/02/17/d1fca5cd-794a-4c34-a2bc-cb256deb18ca/beats-fit-pro-white.jpg?auto=webp&fit=crop&height=630&width=1200
Moviepy - Building video videos/video6.mp4.
MoviePy - Writing audio in video6TEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video videos/video6.mp4

t:   0%|▏                                                                    | 2/960 [00:00<00:50, 18.88it/s, now=None]issue
7
30 Changes We'd Like To See In The Next Pokémon Scarlet & Violet Update - Nintendo Life
Customisation, better settings, and little hats for Koraidon
https://images.nintendolife.com/627e68fc9444e/1280x720.jpg
issue
8
Cyber Monday 2022 gaming laptop deals: the best prices on Asus, Alienware, and more - The Verge
If you’re looking for a gaming-grade laptop, you don’t have to wait. Cyber Monday prices are already here from the likes of Amazon, Best Buy, and Newegg.
https://cdn.vox-cdn.com/thumbor/_c0y5TTodTFDo8ae-QiYqpSFOZs=/0x0:2034x1356/1200x628/filters:focal(1017x678:1018x679)/cdn.vox-cdn.com/uploads/chorus_asset/file/22804770/akrales_210824_4724_0027.jpg
Moviepy - Building video videos/video8.mp4.
MoviePy - Writing audio in video8TEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video videos/video8.mp4

t:   0%|                                                                    | 2/1380 [00:00<01:13, 18.70it/s, now=None]issue
9

Please help me).
Thanks a lot!

**Comment by TheMadrasTechie** [comment]
Hii

can you try running video.py

**Comment by szerzs-collab** [comment]
> 

Nothing happens:(

**Comment by TheMadrasTechie** [comment]
How long are you waiting.

It would take some seconds to give the output.

**Comment by szerzs-collab** [comment]
> some seconds

yes, the process takes a few seconds

**Comment by TheMadrasTechie** [comment]
did u  get ?

**Comment by szerzs-collab** [comment]
> did u get ?

No. Here's a video:
https://drive.google.com/file/d/1b2TbK16RsCTqzEph48VBvvzX6c8hs-B-/view?usp=share_link

**Comment by TheMadrasTechie** [comment]
Check in the videos folder.

Or create a new folder with name **videos**.

**Comment by szerzs-collab** [comment]
Bingooo!!!)

**Comment by szerzs-collab** [comment]
Bingooo!!!)
Excellent! Works! Your script is the best I've seen!
Is it possible to make beautiful transitions somehow?
At least simple).
Thank you friend!

**Comment by TheMadrasTechie** [comment]
I am Working Dude!!!!!!
If I do any changes will update here.

Nice Meeting you...
